// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SendService.proto

package ru.mgt.icp.notificationmanagement.contract.proto;

public interface SendResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool accept = 1;</code>
   * @return The accept.
   */
  boolean getAccept();
}
