// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SendService.proto

package ru.mgt.icp.notificationmanagement.contract.proto;

public final class SendingServiceProto {
  private SendingServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendingNotificationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendingNotificationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendingNotificationRequest_ArgumentsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendingNotificationRequest_ArgumentsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendingNotificationRequest_Template_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendingNotificationRequest_Template_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendingNotificationRequest_Template_PushTemplate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendingNotificationRequest_Template_PushTemplate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendingNotificationRequest_Template_EmailTemplate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendingNotificationRequest_Template_EmailTemplate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendingNotificationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendingNotificationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027proto/SendService.proto\032\027proto/shared/" +
      "uuid.proto\"\202\004\n\032SendingNotificationReques" +
      "t\0226\n\010template\030\001 \001(\0132$.SendingNotificatio" +
      "nRequest.Template\022\016\n\006tabIds\030\002 \003(\t\022\027\n\010gro" +
      "upIds\030\003 \003(\0132\005.Uuid\022=\n\targuments\030\004 \003(\0132*." +
      "SendingNotificationRequest.ArgumentsEntr" +
      "y\0320\n\016ArgumentsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\t:\0028\001\032\221\002\n\010Template\022\013\n\003sms\030\001 \001(\t\022?\n" +
      "\004push\030\002 \001(\01321.SendingNotificationRequest" +
      ".Template.PushTemplate\022A\n\005email\030\003 \001(\01322." +
      "SendingNotificationRequest.Template.Emai" +
      "lTemplate\032+\n\014PushTemplate\022\r\n\005title\030\001 \001(\t" +
      "\022\014\n\004text\030\002 \001(\t\032G\n\rEmailTemplate\022\017\n\007subje" +
      "ct\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\024\n\005files\030\003 \003(\013" +
      "2\005.Uuid\"-\n\033SendingNotificationResponse\022\016" +
      "\n\006accept\030\001 \001(\0102S\n\016SendingService\022A\n\004send" +
      "\022\033.SendingNotificationRequest\032\034.SendingN" +
      "otificationResponseBI\n0ru.mgt.icp.notifi" +
      "cationmanagement.contract.protoB\023Sending" +
      "ServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ru.mgt.icp.proto.shared.UuidProto.getDescriptor(),
        });
    internal_static_SendingNotificationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SendingNotificationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendingNotificationRequest_descriptor,
        new java.lang.String[] { "Template", "TabIds", "GroupIds", "Arguments", });
    internal_static_SendingNotificationRequest_ArgumentsEntry_descriptor =
      internal_static_SendingNotificationRequest_descriptor.getNestedTypes().get(0);
    internal_static_SendingNotificationRequest_ArgumentsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendingNotificationRequest_ArgumentsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_SendingNotificationRequest_Template_descriptor =
      internal_static_SendingNotificationRequest_descriptor.getNestedTypes().get(1);
    internal_static_SendingNotificationRequest_Template_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendingNotificationRequest_Template_descriptor,
        new java.lang.String[] { "Sms", "Push", "Email", });
    internal_static_SendingNotificationRequest_Template_PushTemplate_descriptor =
      internal_static_SendingNotificationRequest_Template_descriptor.getNestedTypes().get(0);
    internal_static_SendingNotificationRequest_Template_PushTemplate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendingNotificationRequest_Template_PushTemplate_descriptor,
        new java.lang.String[] { "Title", "Text", });
    internal_static_SendingNotificationRequest_Template_EmailTemplate_descriptor =
      internal_static_SendingNotificationRequest_Template_descriptor.getNestedTypes().get(1);
    internal_static_SendingNotificationRequest_Template_EmailTemplate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendingNotificationRequest_Template_EmailTemplate_descriptor,
        new java.lang.String[] { "Subject", "Message", "Files", });
    internal_static_SendingNotificationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SendingNotificationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendingNotificationResponse_descriptor,
        new java.lang.String[] { "Accept", });
    ru.mgt.icp.proto.shared.UuidProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
