// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SendService.proto

package ru.mgt.icp.notificationmanagement.contract.proto;

public interface SendingNotificationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendingNotificationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SendingNotificationRequest.Template template = 1;</code>
   * @return Whether the template field is set.
   */
  boolean hasTemplate();
  /**
   * <code>.SendingNotificationRequest.Template template = 1;</code>
   * @return The template.
   */
  ru.mgt.icp.notificationmanagement.contract.proto.SendingNotificationRequest.Template getTemplate();
  /**
   * <code>.SendingNotificationRequest.Template template = 1;</code>
   */
  ru.mgt.icp.notificationmanagement.contract.proto.SendingNotificationRequest.TemplateOrBuilder getTemplateOrBuilder();

  /**
   * <code>repeated string tabIds = 2;</code>
   * @return A list containing the tabIds.
   */
  java.util.List<java.lang.String>
      getTabIdsList();
  /**
   * <code>repeated string tabIds = 2;</code>
   * @return The count of tabIds.
   */
  int getTabIdsCount();
  /**
   * <code>repeated string tabIds = 2;</code>
   * @param index The index of the element to return.
   * @return The tabIds at the given index.
   */
  java.lang.String getTabIds(int index);
  /**
   * <code>repeated string tabIds = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tabIds at the given index.
   */
  com.google.protobuf.ByteString
      getTabIdsBytes(int index);

  /**
   * <code>repeated .Uuid groupIds = 3;</code>
   */
  java.util.List<ru.mgt.icp.proto.shared.Uuid> 
      getGroupIdsList();
  /**
   * <code>repeated .Uuid groupIds = 3;</code>
   */
  ru.mgt.icp.proto.shared.Uuid getGroupIds(int index);
  /**
   * <code>repeated .Uuid groupIds = 3;</code>
   */
  int getGroupIdsCount();
  /**
   * <code>repeated .Uuid groupIds = 3;</code>
   */
  java.util.List<? extends ru.mgt.icp.proto.shared.UuidOrBuilder> 
      getGroupIdsOrBuilderList();
  /**
   * <code>repeated .Uuid groupIds = 3;</code>
   */
  ru.mgt.icp.proto.shared.UuidOrBuilder getGroupIdsOrBuilder(
      int index);

  /**
   * <code>map&lt;string, string&gt; arguments = 4;</code>
   */
  int getArgumentsCount();
  /**
   * <code>map&lt;string, string&gt; arguments = 4;</code>
   */
  boolean containsArguments(
      java.lang.String key);
  /**
   * Use {@link #getArgumentsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getArguments();
  /**
   * <code>map&lt;string, string&gt; arguments = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getArgumentsMap();
  /**
   * <code>map&lt;string, string&gt; arguments = 4;</code>
   */
  /* nullable */
java.lang.String getArgumentsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; arguments = 4;</code>
   */
  java.lang.String getArgumentsOrThrow(
      java.lang.String key);
}
