// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SendService.proto

package ru.mgt.icp.notificationmanagement.contract.proto;

public interface SendRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SendRequest.Template template = 1;</code>
   * @return Whether the template field is set.
   */
  boolean hasTemplate();
  /**
   * <code>.SendRequest.Template template = 1;</code>
   * @return The template.
   */
  ru.mgt.icp.notificationmanagement.contract.proto.SendRequest.Template getTemplate();
  /**
   * <code>.SendRequest.Template template = 1;</code>
   */
  ru.mgt.icp.notificationmanagement.contract.proto.SendRequest.TemplateOrBuilder getTemplateOrBuilder();

  /**
   * <code>repeated string tabIds = 2;</code>
   * @return A list containing the tabIds.
   */
  java.util.List<java.lang.String>
      getTabIdsList();
  /**
   * <code>repeated string tabIds = 2;</code>
   * @return The count of tabIds.
   */
  int getTabIdsCount();
  /**
   * <code>repeated string tabIds = 2;</code>
   * @param index The index of the element to return.
   * @return The tabIds at the given index.
   */
  java.lang.String getTabIds(int index);
  /**
   * <code>repeated string tabIds = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tabIds at the given index.
   */
  com.google.protobuf.ByteString
      getTabIdsBytes(int index);

  /**
   * <code>repeated .Uuid groupIds = 3;</code>
   */
  java.util.List<ru.mgt.icp.proto.shared.Uuid> 
      getGroupIdsList();
  /**
   * <code>repeated .Uuid groupIds = 3;</code>
   */
  ru.mgt.icp.proto.shared.Uuid getGroupIds(int index);
  /**
   * <code>repeated .Uuid groupIds = 3;</code>
   */
  int getGroupIdsCount();
  /**
   * <code>repeated .Uuid groupIds = 3;</code>
   */
  java.util.List<? extends ru.mgt.icp.proto.shared.UuidOrBuilder> 
      getGroupIdsOrBuilderList();
  /**
   * <code>repeated .Uuid groupIds = 3;</code>
   */
  ru.mgt.icp.proto.shared.UuidOrBuilder getGroupIdsOrBuilder(
      int index);

  /**
   * <code>repeated .SendRequest.Argument arguments = 4;</code>
   */
  java.util.List<ru.mgt.icp.notificationmanagement.contract.proto.SendRequest.Argument> 
      getArgumentsList();
  /**
   * <code>repeated .SendRequest.Argument arguments = 4;</code>
   */
  ru.mgt.icp.notificationmanagement.contract.proto.SendRequest.Argument getArguments(int index);
  /**
   * <code>repeated .SendRequest.Argument arguments = 4;</code>
   */
  int getArgumentsCount();
  /**
   * <code>repeated .SendRequest.Argument arguments = 4;</code>
   */
  java.util.List<? extends ru.mgt.icp.notificationmanagement.contract.proto.SendRequest.ArgumentOrBuilder> 
      getArgumentsOrBuilderList();
  /**
   * <code>repeated .SendRequest.Argument arguments = 4;</code>
   */
  ru.mgt.icp.notificationmanagement.contract.proto.SendRequest.ArgumentOrBuilder getArgumentsOrBuilder(
      int index);
}
