// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SendService.proto

package ru.mgt.icp.notificationmanagement.contract.proto;

public final class StatusServiceProto {
  private StatusServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendRequest_Argument_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendRequest_Argument_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendRequest_Template_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendRequest_Template_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendRequest_Template_PushTemplate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendRequest_Template_PushTemplate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendRequest_Template_EmailTemplate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendRequest_Template_EmailTemplate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027proto/SendService.proto\032\027proto/shared/" +
      "uuid.proto\032\027google/rpc/status.proto\"\242\003\n\013" +
      "SendRequest\022\'\n\010template\030\001 \001(\0132\025.SendRequ" +
      "est.Template\022\016\n\006tabIds\030\002 \003(\t\022\027\n\010groupIds" +
      "\030\003 \003(\0132\005.Uuid\022(\n\targuments\030\004 \003(\0132\025.SendR" +
      "equest.Argument\032(\n\010Argument\022\r\n\005title\030\001 \001" +
      "(\t\022\r\n\005value\030\002 \001(\t\032\354\001\n\010Template\022\013\n\003sms\030\001 " +
      "\001(\t\0220\n\004push\030\002 \001(\0132\".SendRequest.Template" +
      ".PushTemplate\0222\n\005email\030\003 \001(\0132#.SendReque" +
      "st.Template.EmailTemplate\032+\n\014PushTemplat" +
      "e\022\r\n\005title\030\001 \001(\t\022\014\n\004text\030\002 \001(\t\032@\n\rEmailT" +
      "emplate\022\017\n\007subject\030\001 \001(\t\022\017\n\007message\030\002 \001(" +
      "\t\022\r\n\005files\030\003 \003(\t\"\036\n\014SendResponse\022\016\n\006acce" +
      "pt\030\001 \001(\0102[\n\013SendService\022#\n\004send\022\014.SendRe" +
      "quest\032\r.SendResponse\022\'\n\010sendTest\022\014.SendR" +
      "equest\032\r.SendResponseBH\n0ru.mgt.icp.noti" +
      "ficationmanagement.contract.protoB\022Statu" +
      "sServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ru.mgt.icp.proto.shared.UuidProto.getDescriptor(),
          com.google.rpc.StatusProto.getDescriptor(),
        });
    internal_static_SendRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendRequest_descriptor,
        new java.lang.String[] { "Template", "TabIds", "GroupIds", "Arguments", });
    internal_static_SendRequest_Argument_descriptor =
      internal_static_SendRequest_descriptor.getNestedTypes().get(0);
    internal_static_SendRequest_Argument_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendRequest_Argument_descriptor,
        new java.lang.String[] { "Title", "Value", });
    internal_static_SendRequest_Template_descriptor =
      internal_static_SendRequest_descriptor.getNestedTypes().get(1);
    internal_static_SendRequest_Template_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendRequest_Template_descriptor,
        new java.lang.String[] { "Sms", "Push", "Email", });
    internal_static_SendRequest_Template_PushTemplate_descriptor =
      internal_static_SendRequest_Template_descriptor.getNestedTypes().get(0);
    internal_static_SendRequest_Template_PushTemplate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendRequest_Template_PushTemplate_descriptor,
        new java.lang.String[] { "Title", "Text", });
    internal_static_SendRequest_Template_EmailTemplate_descriptor =
      internal_static_SendRequest_Template_descriptor.getNestedTypes().get(1);
    internal_static_SendRequest_Template_EmailTemplate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendRequest_Template_EmailTemplate_descriptor,
        new java.lang.String[] { "Subject", "Message", "Files", });
    internal_static_SendResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendResponse_descriptor,
        new java.lang.String[] { "Accept", });
    ru.mgt.icp.proto.shared.UuidProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
